package ni.edu.uni.programacion.views.panels;

import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Axel Moreno
 */
public class PnlViewVehicle extends javax.swing.JPanel
{

	public PnlViewVehicle() 
        {
		initComponents();
	}

	public JTable getTbVehicles() 
        {
		return TbVehicles;
	}

	public void setTbVehicles(JTable TbVehicles)
        {
		this.TbVehicles = TbVehicles;
	}

	public JTextField getTxtSearch() 
        {
		return TxtSearch;
	}

	public void setTxtSearch(JTextField TxtSearch) 
        {
		this.TxtSearch = TxtSearch;
	}

	public JComboBox<String> getCmbSearch()
        {
		return cmbSearch;
	}

	public void setCmbSearch(JComboBox<String> cmbSearch) 
        {
		this.cmbSearch = cmbSearch;
	}
	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        TbVehicles = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cmbSearch = new javax.swing.JComboBox<>();
        TxtSearch = new javax.swing.JTextField();

        setLayout(new java.awt.BorderLayout());

        jScrollPane.setBackground(new java.awt.Color(0, 204, 204));

        TbVehicles.setBackground(new java.awt.Color(153, 153, 153));
        TbVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "StockNumber", "Year", "Make", "Model", "Style", "Vin", "Ext. Color", "Int. Color", "Miles", "Price", "Transmission", "Engine", "Image", "Status"
            }
        ));
        jScrollPane.setViewportView(TbVehicles);

        add(jScrollPane, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 51, 255));

        cmbSearch.setBackground(new java.awt.Color(51, 255, 255));
        jPanel1.add(cmbSearch);
        jPanel1.add(TxtSearch);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbVehicles;
    private javax.swing.JTextField TxtSearch;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    // End of variables declaration//GEN-END:variables
}
